// Pre-generates a pool of puzzles per difficulty tier and writes js/puzzle-pool.js.
// Run this offline/on demand — some tiers (Rooftop Sniper especially) are slow
// to hit an exact technique-tier match, so this is not something the app
// should ever do live in the browser. The game picks a random puzzle from
// this pre-built pool at runtime instead (see js/pool.js).
//
// Usage: node scripts/generate-pool.js [poolSizePerTier]

const fs = require("fs");
const path = require("path");
const { DIFFICULTY_LEVELS, generatePuzzle } = require("../js/generator.js");

const poolSizePerTier = Number(process.argv[2]) || 20;
const outputPath = path.join(__dirname, "..", "js", "puzzle-pool.js");

const pool = {};

for (const level of DIFFICULTY_LEVELS) {
  const start = Date.now();
  const puzzles = [];

  for (let i = 0; i < poolSizePerTier; i++) {
    const puzzle = generatePuzzle({
      N: level.N,
      targetTier: level.tier,
      seed: level.tier * 10_000_000 + i,
      maxAttempts: 50000,
    });
    if (!puzzle) {
      console.error(`  ${level.name} #${i}: FAILED to generate within attempt budget — aborting`);
      process.exit(1);
    }
    puzzles.push({
      N: puzzle.N,
      regionOf: puzzle.regionOf,
      solution: puzzle.solution,
      maxTierUsed: puzzle.maxTierUsed,
    });
  }

  pool[level.key] = puzzles;
  console.log(`${level.name}: generated ${puzzles.length} puzzles in ${Date.now() - start}ms`);
}

const fileContents = `// Auto-generated by scripts/generate-pool.js — do not edit by hand.
// Regenerate with: node scripts/generate-pool.js [poolSizePerTier]
const PUZZLE_POOL = ${JSON.stringify(pool)};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { PUZZLE_POOL };
} else if (typeof window !== "undefined") {
  window.CatdokuPuzzlePool = { PUZZLE_POOL };
}
`;

fs.writeFileSync(outputPath, fileContents);
console.log(`\nWrote ${outputPath}`);
